dist: bionic
language: node_js
node_js:
  - 13
install:
  - npm install
script:
  - ./node_modules/@angular/cli/bin/ng build --prod
  - tar cf - dist/ | gzip --best > cchits-ng.frontend.prod.tar.gz
  - rm -rf dist
  - ./node_modules/@angular/cli/bin/ng build --staging
  - tar cf - dist/ | gzip --best > cchits-ng.frontend.staging.tar.gz
  - rm -rf dist
