dist: bionic
language: node_js
node_js:
  - 13
before_install:
  - openssl aes-256-cbc -K $encrypted_86635fc2351d_key -iv $encrypted_86635fc2351d_iv -in travis-ci.key.enc -out ./travis-ci.key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./travis-ci.key
  - echo -e "Host skym.fr\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./travis-ci.key
install:
  - npm install
script:
  - rm -rf dist
  - ./node_modules/@angular/cli/bin/ng build --configuration=staging
  - tar cf - dist/ | gzip --best > cchits-ng.frontend.staging.tar.gz
  - scp -i ./travis-ci.key cchits-ng.frontend.staging.tar.gz cchits_staging@staging.cchits.net:deploy/
  - rm -rf dist
  - ./node_modules/@angular/cli/bin/ng build --configuration=test
  - tar cf - dist/ | gzip --best > cchits-ng.frontend.test.tar.gz
  - scp -i ./travis-ci.key cchits-ng.frontend.test.tar.gz travis@skym.fr:deploy/
