dist: bionic
language: node_js
node_js:
  - 13
before_install:
  - openssl aes-256-cbc -K $encrypted_86635fc2351d_key -iv $encrypted_86635fc2351d_iv -in travis-ci.key.enc -out ./travis-ci.key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host skym.fr\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
install:
  - npm install
script:
  - ./node_modules/@angular/cli/bin/ng build --prod
  - tar cf - dist/ | gzip --best > cchits-ng.frontend.prod.tar.gz
  - rm -rf dist
  - scp -i ./travis-ci.key cchits-ng.frontend.prod.tar.gz travis@skym.fr:deploy/
  - ./node_modules/@angular/cli/bin/ng build
  - tar cf - dist/ | gzip --best > cchits-ng.frontend.staging.tar.gz
  - rm -rf dist
  - scp -i ./travis-ci.key cchits-ng.frontend.staging.tar.gz travis@skym.fr:deploy/
